name: Upload a local file to S3
description: This action uploads a local file to S3 via cURL

inputs:
  access-key-id:
    description: >
      The access key ID. You can find it anytime in the account description
      (Object storage -> Accounts -> Your account name)
    required: true
  secret-access-key:
    description: >
      The secret access key. You can see it only at the time you create the
      account
    required: true
  bucket:
    description: The bucket name
    required: true
  source:
    description: The source file path
    required: true
  destination:
    description: >
      The destination file path in the bucket, including the file name
    required: true
  endpoint:
    description: The endpoint URL without protocol prefix
    required: false
    default: hb.bizmrg.com
  content-type:
    description: The content type for the content being uploaded
    required: false
    default: application/x-compressed-tar

runs:
  using: composite
  steps:
    - name: Upload the file to S3
      shell: bash
      run: |
        if [ ! -f ${{ inputs.source }} ]; then 
            echo "Source file doesn't exist or is not a regular file"
            exit 1
        fi
        
        keyID="${{ inputs.access-key-id }}"
        secretKey="${{ inputs.secret-access-key }}"
        bucket="${{ inputs.bucket }}"
        destination="${{ inputs.destination }}"
        endpoint="${{ inputs.endpoint }}"
        contentType="${{ inputs.content-type }}"
        dateValue="$(date -R)"
        stringToSign="PUT\n\n${contentType}\n${dateValue}\n/${bucket}/${destination}"
        signature="$(echo -en ${stringToSign} | openssl sha1 -hmac ${secretKey} -binary | base64)"
        
        curl -X PUT -T "${{ inputs.source }}" \
          -H "Host: ${bucket}.${endpoint}" \
          -H "Date: ${dateValue}" \
          -H "Content-Type: ${contentType}" \
          -H "Authorization: AWS ${keyID}:${signature}" \
          -f https://${bucket}.${endpoint}/${destination}
