name: Copy the files from the runner to the S3 bucket
description: Copy the files from the runner to the S3 bucket

inputs:
  s3-access-key-id:
    description: >
      S3 access key ID. You can find it anytime in the account description
      (Object storage -> Accounts -> Your account name).
    required: true
  s3-secret-access-key:
    description: >
      S3 secret access key. You can see it only at the time you create the
      account.
    required: true
  s3-region:
    description: >
      The region set in your S3 endpoint. You can find it in the documentation
      of your S3 storage, i.e.
      https://mcs.mail.ru/docs/ru/base/s3/quick-start/create-bucket.
    required: false
    default: ru-msk
  bucket:
    description: The name of the S3 bucket.
    required: true
  source:
    description: The path to the file or directory you want to save to S3.
    required: true
  destination:
    description: >
      The path in the bucket with the file name. If you want to store the file
      in the bucket root, destination must be the file name.
    required: true
  endpoint:
    description: >
      The URL of your S3 storage to get the access to the uploaded files without protocol prefix.
    required: false
    default: hb.bizmrg.com

runs:
  using: composite
  steps:
    - name: Upload the file to S3 if the input file exists
      shell: bash
      run: |
        if [[ ! -e ${{ inputs.source }} ]]; then
          exit 0
        fi
        
        bucket=${{ inputs.bucket }}
        contentType="application/x-compressed-tar"
        dateValue=`date -R`
        resource=${{ inputs.destination }}
        stringToSign="PUT\n\n${contentType}\n${dateValue}\n/${bucket}/${resource}"
        s3Key='${{ inputs.s3-access-key-id }}'
        s3Secret='${{ inputs.s3-secret-access-key }}'
        signature=`echo -en ${stringToSign} | openssl sha1 -hmac ${s3Secret} -binary | base64`
        
        curl -X PUT -T "${{ inputs.source }}" \
          -H "Host: ${bucket}.hb.bizmrg.com" \
          -H "Date: ${dateValue}" \
          -H "Content-Type: ${contentType}" \
          -H "Authorization: AWS ${s3Key}:${signature}" \
          https://${bucket}.hb.bizmrg.com/${resource}
