---
name: 'Clean workspace'
description: 'Clean workspace directory after previous workflow run'
runs:
  using: 'composite'
  steps:
    - run: |
        set -e
        shopt -s dotglob
        whoami
        rm -rfv ${{ github.workspace }}/*
      shell: bash
