name: 'Create Pull Request for Submodule Update'
description: >
  This action updates a submodule of the target repository in a feature branch
  and opens a pull request against the main branch to commit changes. If there
  is an open pull request already, the action will just force-push the feature
  branch
author: 'foxzi'

branding:
  icon: 'git-pull-request'
  color: 'green'

inputs:
  github_token:
    description: >
      The GitHub token of a user with `write` permissions in the target
      repository. Provide this token as an action secret
    required: true
  repository:
    description: 'The full name of the target repository: <owner>/<repo>'
    required: true
  checkout_branch:
    description: 'The target repository branch to checkout'
    required: false
    default: 'master'
  feature_branch:
    description: 'The target repository feature branch'
    required: false
    default: 'bot/update-submodule'
  submodule:
    description: 'The submodule path to update in the target repository'
    required: true
  update_to:
    description: >
      The git ref to update the submodule to (branch, tag, or commit SHA)
    required: false
    default: 'master'
  create_pr:
    description: "Enable or disable creating a pull request"
    required: false
    default: 'true'
  pr_against_branch:
    description: >
      The target repository branch to open a pull request against.
      Usually the same as `checkout_branch`
    required: false
    default: 'master'
  pr_title:
    description: 'The title of the pull request'
    required: false
    default: '[Auto-generated] Update submodule'
  pr_description:
    description: 'The description of the pull request'
    required: false
    default: 'Update submodule.'
  commit_user:
    description: 'The user for the commit'
    default: 'TarantoolBot'
    required: false
  commit_user_email:
    description: 'The user email for the commit'
    default: 'bot@tarantool.io'
    required: false
  commit_message:
    description: 'The message for the commit'
    default: 'Update submodule'
    required: false
outputs:
  sha:
    description: 'Full SHA1 of resulting commit'
    value: ${{ steps.create-branch.outputs.sha }}
  sha7:
    description: 'Short SHA1 of resulting commit'
    value: ${{ steps.create-branch.outputs.sha7 }}

runs:
  using: composite
  steps:
    - name: Prepare checkout
      uses: tarantool/actions/prepare-checkout@master

    - name: Checkout the target repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github_token }}
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.checkout_branch }}
        submodules: true
        fetch-depth: 0

    - name: Create the new branch and push changes
      id: create-branch
      shell: bash
      run: |
        pushd ${{ inputs.submodule }}
        git fetch origin ${{ inputs.update_to }}
        git checkout FETCH_HEAD
        popd

        git config user.name ${{ inputs.commit_user }}
        git config user.email ${{ inputs.commit_user_email }}

        git checkout -b "${{ inputs.feature_branch }}"
        if [[ $(git status) =~ .*"nothing to commit".* ]]; then 
          echo "status=nothing-to-commit" >> $GITHUB_OUTPUT
          exit 0
        fi
        git commit -am "${{ inputs.commit_message }}"
        git push --force origin "${{ inputs.feature_branch }}"

        # add new commit's SHA to action's outputs
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        echo "sha7=$(git rev-parse HEAD | head -c 7)" >> $GITHUB_OUTPUT

    - name: Create a pull request against the main branch
      if: inputs.create_pr == 'true' &&
        steps.create-branch.outputs.status != 'nothing-to-commit'
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          await github.rest.pulls.create({
            owner: '${{ inputs.repository }}'.split('/')[0].trim(),
            repo: '${{ inputs.repository }}'.split('/')[1].trim(),
            head: '${{ inputs.feature_branch }}',
            base: '${{ inputs.pr_against_branch }}',
            title: '${{ inputs.pr_title }}',
            body: '${{ inputs.pr_description }}',
          });
      continue-on-error: true
