name: Remove a git reference via GitHub API
description: >
  This action removes a git branch,
  from a repository on GitHub with an API call.
  It is a convenient way to remove temporary branches, like
  those created by `tarantool/actions/update-submodule`.
  
  Note: removing tags is not supported yet.

inputs:
  repository:
    description: Repository name (<owner>/<repo>)
    required: true
  ref:
    description: Git reference to remove
    required: true
  token:
    description: GitHub personal access token (PAT)
    required: true

runs:
  using: composite
  steps:
    - name: Remove reference ${{ inputs.ref }} from ${{ inputs.repository }}
      uses: actions/github-script@v6
      continue-on-error: true
      with:
        github-token: ${{ inputs.token }}
        script: |
          const fullRepoName = "${{ inputs.repository }}".split("/")
          await github.request('DELETE /repos/{owner}/{repo}/git/refs/heads/{ref}', {
            owner: fullRepoName[0],
            repo: fullRepoName[1],
            ref: "${{ inputs.ref }}"
          })
