---
name: Lint YAML code

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: YAML Lint and Annotate
        uses: Staffbase/yamllint-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target-path: .
